<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120811204943 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE lelesys_eventsexample_domain_model_event (flow3_persistence_identifier VARCHAR(40) NOT NULL, createdby VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, place VARCHAR(255) NOT NULL, starttime DATETIME NOT NULL, endtime DATETIME NOT NULL, timecreated DATETIME NOT NULL, INDEX IDX_8C7B777446D262E0 (createdby), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_eventsexample_domain_model_event ADD CONSTRAINT FK_8C7B777446D262E0 FOREIGN KEY (createdby) REFERENCES typo3_flow3_security_account (flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE lelesys_eventsexample_domain_model_event");
	}
}

?>