# TYPO3.FLOW3 settings override
TYPO3:
  FLOW3:
    error:
      exceptionHandler:
        # Defines the global, last-resort exception handler.
        # The specified class must implement \TYPO3\FLOW3\Error\ExceptionHandlerInterface
        # Overridden to silently report exceptions for REST API calls
        className: Lelesys\EventsExample\Error\ProductionExceptionHandler
      errorHandler:
        # Defines which errors should result in an exception thrown - all other error
        # levels will be silently ignored. Only errors that can be handled in an
        # user-defined error handler are affected, of course.
        exceptionalErrors: [%E_USER_ERROR%, %E_RECOVERABLE_ERROR%]
    mvc:
      # Object name of the controller to use if no other controller could be resolved
      # matching the request.
      notFoundController: Lelesys\EventsExample\Controller\NotFoundController

# Lelesys.EventsExample settings
Lelesys:
  EventsExample:
    event:
      dateTimeFormat: 'Y-m-d H:i:s'